name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: python -m pytest -v


  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build Docker image
        run: docker build -t calculator-api:${{ github.sha }} .

      - name: Show Docker images
        run: docker images


  semgrep:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep scan --config=auto --json --output semgrep-report.json .
        continue-on-error: true

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json


  trivy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: json
          output: trivy-fs-report.json
          severity: HIGH,CRITICAL
          exit-code: "0"

      - name: Build Docker image for Trivy
        run: docker build -t calculator-api:trivy .

      - name: Trivy Docker image scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: calculator-api:trivy
          format: json
          output: trivy-image-report.json
          severity: HIGH,CRITICAL
          exit-code: "0"

      - name: Upload Trivy reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-fs-report.json
            trivy-image-report.json